#!/bin/bash
# Copyright (c) 2012 Peter Varkoly <peter@varkoly.de> Nürnberg, Germany.  All rights reserved.

if [ "$1" = "--help" -o  "$1" = "-h" ]
then
	echo 'Usage: /usr/share/oss/tools/delete-ox-rights [OPTION]'
	echo 'With this script we can delete the openexchage privileges (for Students).'
	echo
	echo 'Options :'
	echo 'Mandatory parameters :'
	echo "		No need for mandatory parameters. (There's no need for parameters for running this script.)"
	echo 'Optional parameters :'
	echo '		-h,   --help         Display this help.'
	echo '		-d,   --description  Display the descriptiont.'
	exit
fi

if [ "$1" = "--description" -o  "$1" = "-d" ]
then
	echo 'NAME:'
	echo '	delete-ox-rights'
	echo 'DESCRIPTION:'
	echo '	With this script we can delete the openexchage privileges (for Students).'
	echo 'PARAMETERS:'
	echo '	MANDATORY:'
	echo "		                    : No need for mandatory parameters. (There's no need for parameters for running this script.)"
	echo '	OPTIONAL:'
	echo '		-h,   --help        : Display this help.(type=boolean)'
	echo '		-d,   --description : Display the descriptiont.(type=boolean)'
	exit
fi

for i in $( oss_get_users students )
do
    for j in data cont proj doc knowl bookm pin
    do
        echo "update usr_general_rights set ${j}_u='n', ${j}_r='n', ${j}_d='n' where login = '$i';" | psql -U openexchange openexchange 
    done
    echo "update usr_general_rights set forum_n='n' where login = '$i';"  | psql -U openexchange openexchange
done
