#!/bin/bash
# Copyright (c) 2012 Peter Varkoly <peter@varkoly.de> Nürnberg, Germany.  All rights reserved.

if [ "$1" = "--help" -o  "$1" = "-h" ]
then
	echo 'Usage: /usr/share/oss/tools/make_mail_to_all [OPTION]'
	echo "With this script we're doing the mail sending to the MailToAll module."
	echo
	echo 'Options :'
	echo 'Mandatory parameters :'
	echo "		No need for mandatory parameters. (There's no need for parameters for running this script.)"
	echo 'Optional parameters :'
	echo '		-h,   --help         Display this help.'
	echo '		-d,   --description  Display the descriptiont.'
	exit
fi

if [ "$1" = "--description" -o  "$1" = "-d" ]
then
	echo 'NAME:'
	echo '	make_mail_to_all'
	echo 'DESCRIPTION:'
	echo "	With this script we're doing the mail sending to the MailToAll module."
	echo 'PARAMETERS:'
	echo '	MANDATORY:'
	echo "		                    : No need for mandatory parameters. (There's no need for parameters for running this script.)"
	echo '	OPTIONAL:'
	echo '		-h,   --help        : Display this help.(type=boolean)'
	echo '		-d,   --description : Display the descriptiont.(type=boolean)'
	exit
fi

. /tmp/MAIL_TO_ALL
ATTACH=""

dos2unix /tmp/MAIL_TO_ALL-BODY
cat /tmp/MAIL_TO_ALL-BODY|mail -s "$SUBJECT" -r "$MAILFROM" $ATTACH "$MAILTO"
rm -f /tmp/MAIL_TO_ALL*
