#!/bin/bash
# Copyright (c) 2012 Peter Varkoly <peter@varkoly.de> Nürnberg, Germany.  All rights reserved.

if [ "$1" = "--help" -o  "$1" = "-h" ]
then
	echo 'Usage: /usr/share/oss/tools/send_invoice_to_mail [OPTION]'
	echo 'This script sends out the emails about the invoices to the users.'
	echo
	echo 'Options :'
	echo 'Mandatory parameters :'
	echo "          No need for mandatory parameters. (There's no need for parameters for running this script.)"
	echo 'Optional parameters :'
	echo '          -h,   --help         Display this help.'
	echo '          -d,   --description  Display the descriptiont.'
	exit
fi

if [ "$1" = "--description" -o  "$1" = "-d" ]
then
	echo 'NAME:'
	echo '	send_invoice_to_mail'
	echo 'DESCRIPTION:'
	echo '	This script sends out the emails about the invoices to the users.'
	echo 'PARAMETERS:'
	echo '	MANDATORY:'
	echo "                              : No need for mandatory parameters. (There's no need for parameters for running this script.)"
	echo '	OPTIONAL:'
	echo '		-h,   --help        : Display this help.(type=boolean)'
	echo '		-d,   --description : Display the descriptiont.(type=boolean)'
	exit
fi

. /tmp/SEND_INVOCE
ATTACH=" -a $INVOICE"

dos2unix /tmp/SEND_INVOCE-BODY
cat /tmp/SEND_INVOCE-BODY|mail -s "$SUBJECT" -r "$MAILFROM" $ATTACH "$MAILTO"
rm -f /tmp/SEND_INVOCE*
