#!/bin/bash
# Copyright (c) 2012 Peter Varkoly <peter@varkoly.de> Nürnberg, Germany.  All rights reserved.

if [ ! -d "/home/profile/$1" ]
then
  mkdir -m 700 /home/profile/$1
  chown $1 /home/profile/$1
fi

