#!/bin/bash
# Copyright (c) 2012 Peter Varkoly <peter@varkoly.de> Nürnberg, Germany.  All rights reserved.
role=$1;
if [ -z $role ]
then
    role='*'
fi
ldapsearch -x -LLL "(&(objectclass=schoolAccount)(role=$role))" uid | grep uid: | sed 's/uid: //'
